#!/usr/bin/env python3
"""
Generate a static Bad Apple frame header for the Mode0 fun demo.

The current SDRAM-backed bitmap proof path is tied to the Scenario 45 row
fetcher:
  - 640 visible pixels per row -> 80 active bytes
  - fixed 128-byte SDRAM stride per row
  - host-side 1bpp bitmap data

This script downloads the source video on demand, extracts one frame,
converts it to 640x240 monochrome, pads each row to the fixed 128-byte
stride, and emits a C header consumed by the Pico demo firmware.
"""

from __future__ import annotations

import argparse
import pathlib
import shutil
import subprocess
import sys
import tempfile

from PIL import Image


DEFAULT_URL = "https://raw.githubusercontent.com/CalvinLoke/bad-apple/master/BadApple.mp4"
DEFAULT_FRAME_TIME = 60.0
WIDTH = 640
HEIGHT = 240
ACTIVE_BYTES_PER_ROW = WIDTH // 8
ROW_STRIDE_BYTES = 128
ATTR_BYTE = 0x47  # bright white ink on black paper


def run(cmd: list[str]) -> None:
    subprocess.run(cmd, check=True)


def ensure_video(path: pathlib.Path, url: str) -> None:
    if path.exists():
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    run(["curl", "-L", "--fail", "-o", str(path), url])


def make_bitmap_words(frame_png: pathlib.Path) -> list[int]:
    with Image.open(frame_png) as img:
        img = img.convert("L")
        # Resize first, then threshold to preserve silhouette edges.
        img = img.resize((WIDTH, HEIGHT), resample=Image.Resampling.LANCZOS)
        bw = img.point(lambda px: 255 if px >= 128 else 0, mode="1")

    words: list[int] = []
    for y in range(HEIGHT):
        row_bytes = bytearray()
        for x0 in range(0, WIDTH, 8):
            packed = 0
            for bit in range(8):
                pixel = bw.getpixel((x0 + bit, y))
                if pixel:
                    packed |= 1 << (7 - bit)
            row_bytes.append(packed)
        row_bytes.extend(b"\x00" * (ROW_STRIDE_BYTES - ACTIVE_BYTES_PER_ROW))
        for i in range(0, len(row_bytes), 2):
            words.append(row_bytes[i] | (row_bytes[i + 1] << 8))
    return words


def emit_header(out_path: pathlib.Path, frame_time: float, source_path: pathlib.Path, words: list[int]) -> None:
    out_path.parent.mkdir(parents=True, exist_ok=True)
    with out_path.open("w", encoding="ascii") as f:
        f.write("/* Auto-generated by scripts/bad_apple/generate_bad_apple_frame.py. */\n")
        f.write("#ifndef BAD_APPLE_FRAME_H\n")
        f.write("#define BAD_APPLE_FRAME_H\n\n")
        f.write("#include <stdint.h>\n\n")
        f.write(f"#define BAD_APPLE_SOURCE_URL \"{DEFAULT_URL}\"\n")
        f.write(f"#define BAD_APPLE_SOURCE_FILE \"{source_path.name}\"\n")
        f.write(f"#define BAD_APPLE_FRAME_TIME_SEC {frame_time:.3f}f\n")
        f.write(f"#define BAD_APPLE_BITMAP_BASE 0x3000u\n")
        f.write(f"#define BAD_APPLE_ATTR_BASE 0x4000u\n")
        f.write(f"#define BAD_APPLE_FRAME_WIDTH {WIDTH}u\n")
        f.write(f"#define BAD_APPLE_FRAME_HEIGHT {HEIGHT}u\n")
        f.write(f"#define BAD_APPLE_ACTIVE_BYTES_PER_ROW {ACTIVE_BYTES_PER_ROW}u\n")
        f.write(f"#define BAD_APPLE_ROW_STRIDE_BYTES {ROW_STRIDE_BYTES}u\n")
        f.write(f"#define BAD_APPLE_ATTR_BYTE 0x{ATTR_BYTE:02X}u\n")
        f.write(f"#define BAD_APPLE_BITMAP_WORD_COUNT {len(words)}u\n\n")
        f.write("static const uint16_t bad_apple_bitmap_words[BAD_APPLE_BITMAP_WORD_COUNT] = {\n")
        for i in range(0, len(words), 8):
            chunk = ", ".join(f"0x{w:04X}" for w in words[i:i + 8])
            f.write(f"    {chunk},\n")
        f.write("};\n\n")
        f.write("#endif /* BAD_APPLE_FRAME_H */\n")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--video",
        default="/home/itadmin/github/spinalhdlVDP/rt_samples/bad_apple/source/BadApple.mp4",
        help="Path to local video cache",
    )
    parser.add_argument(
        "--source-url",
        default=DEFAULT_URL,
        help="Download URL used when --video is missing",
    )
    parser.add_argument(
        "--frame-time",
        type=float,
        default=DEFAULT_FRAME_TIME,
        help="Timestamp in seconds for the extracted frame",
    )
    parser.add_argument(
        "--output-header",
        default="/home/itadmin/github/spinalhdlVDP/firmware/test_mode0_bad_apple/bad_apple_frame.h",
        help="Header output path",
    )
    args = parser.parse_args()

    video_path = pathlib.Path(args.video)
    out_path = pathlib.Path(args.output_header)
    ensure_video(video_path, args.source_url)

    ffmpeg = shutil.which("ffmpeg")
    if not ffmpeg:
        raise SystemExit("ffmpeg is required")

    with tempfile.TemporaryDirectory(prefix="bad_apple_") as tmpdir:
        frame_png = pathlib.Path(tmpdir) / "frame.png"
        run(
            [
                ffmpeg,
                "-y",
                "-ss",
                f"{args.frame_time:.3f}",
                "-i",
                str(video_path),
                "-frames:v",
                "1",
                "-update",
                "1",
                str(frame_png),
            ]
        )
        words = make_bitmap_words(frame_png)

    emit_header(out_path, args.frame_time, video_path, words)
    print(f"Wrote {out_path} ({len(words)} words)", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
