/* Auto-generated by scripts/assets/png_to_vdp_assets.py. */
#ifndef ASSET_DEMO_META_H
#define ASSET_DEMO_META_H

#define ASSET_DEMO_KIND "tilesheet"
#define ASSET_DEMO_INPUT "demo.png"
#define ASSET_DEMO_TILE_W 16u
#define ASSET_DEMO_TILE_H 16u
#define ASSET_DEMO_BPP 4u
#define ASSET_DEMO_TILES_X 1u
#define ASSET_DEMO_TILES_Y 1u
#define ASSET_DEMO_TILES 1u
#define ASSET_DEMO_SDRAM_BASE 0x6000u
#define ASSET_DEMO_TILES_BIN "asset_demo_tiles.h"
#define ASSET_DEMO_PALETTE_BIN "asset_demo_palette.h"

#endif /* ASSET_DEMO_META_H */
