/* Auto-generated by scripts/assets/bin_to_c_array.py. */
#ifndef ASSET_DEMO_TILES_H
#define ASSET_DEMO_TILES_H

#include <stdint.h>

#define ASSET_DEMO_TILES_WORD_COUNT 8u

static const uint16_t asset_demo_tiles[ASSET_DEMO_TILES_WORD_COUNT] = {
    0x1111u, 0x2222u, 0x3333u, 0x4444u,
    0x5555u, 0x6666u, 0x7777u, 0x8888u,
};

#endif /* ASSET_DEMO_TILES_H */
