#!/usr/bin/env python3
"""
Convert a raw binary blob into a C header with a static array.

Intended for `png_to_vdp_assets.py` outputs that are consumed by firmware
upload code. The default `words` mode emits `uint16_t` data suitable for
`vdp_upload_asset()` / `vdp_sdram_write()`.
"""

from __future__ import annotations

import argparse
import pathlib
import re


def c_ident(text: str) -> str:
    ident = re.sub(r"[^0-9A-Za-z]+", "_", text).strip("_")
    if not ident:
        ident = "VDP_ASSET"
    if ident[0].isdigit():
        ident = f"_{ident}"
    return ident.upper()


def ensure_dir(path: pathlib.Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)


def format_words(data: bytes) -> tuple[str, int]:
    if len(data) % 2:
        raise SystemExit("word mode requires an even number of bytes")
    words = []
    for i in range(0, len(data), 2):
        words.append(f"0x{data[i] | (data[i + 1] << 8):04X}u")
    return ", ".join(words), len(words)


def format_bytes(data: bytes) -> tuple[str, int]:
    return ", ".join(f"0x{b:02X}u" for b in data), len(data)


def emit_header(path: pathlib.Path, symbol: str, data: bytes, mode: str, source: pathlib.Path) -> None:
    guard = c_ident(path.stem)
    sym = c_ident(symbol)

    if mode == "auto":
        mode = "words" if len(data) % 2 == 0 else "bytes"

    if mode == "words":
        values, count = format_words(data)
        c_type = "uint16_t"
        suffix = "_WORD_COUNT"
    elif mode == "bytes":
        values, count = format_bytes(data)
        c_type = "uint8_t"
        suffix = "_BYTE_COUNT"
    else:
        raise SystemExit(f"unsupported mode: {mode}")

    ensure_dir(path)
    with path.open("w", encoding="utf-8") as f:
        f.write(f"#ifndef {guard}\n")
        f.write(f"#define {guard}\n\n")
        f.write("/* Auto-generated by scripts/assets/bin_to_c_array.py. */\n")
        f.write(f"/* Source: {source} */\n\n")
        f.write("#include <stdint.h>\n\n")
        f.write(f"#define {sym}{suffix} {count}u\n\n")
        f.write(f"static const {c_type} {sym}[{sym}{suffix}] = {{\n")
        if values:
            elems = values.split(", ")
            for i in range(0, len(elems), 8):
                f.write(f"    {', '.join(elems[i:i + 8])},\n")
        f.write("};\n\n")
        f.write(f"#endif /* {guard} */\n")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("input", type=pathlib.Path, help="input binary blob")
    parser.add_argument("output", type=pathlib.Path, help="output C header")
    parser.add_argument(
        "--symbol",
        default=None,
        help="C symbol prefix to use (defaults to output stem)",
    )
    parser.add_argument(
        "--mode",
        choices=("auto", "words", "bytes"),
        default="words",
        help="array element size",
    )
    args = parser.parse_args()

    data = args.input.read_bytes()
    symbol = args.symbol or args.output.stem
    emit_header(args.output, symbol, data, args.mode, args.input)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
